name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: App.test.js
      id: app-test-js
      uses: education/autograding-command-grader@v1
      with:
        test-name: App.test.js
        setup-command: npm install
        command: npm test a
        timeout: 60
        max-score: 100
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        APP-TEST-JS_RESULTS: "${{steps.app-test-js.outputs.result}}"
      with:
        runners: app-test-js
